### PR TITLE
[PATCH v4] Update supported DPDK version to 20.11

### PR DESCRIPTION
**Pull request by MatiasElo**
V3:
- Replace global _GNU_SOURCE define with `#include <odp_posix_extensions.h>`

### CODE REVIEW

**Review by psavol — APPROVED** [review]

**Comment by chrhong** [comment]
@MatiasElo After update dpdk to 20.11.5, I notice the dpdk libs is changed.
Eg: librte_pmd* --> librte_net*
So I think this file needs some update. Thanks.

**Comment by MatiasElo** [comment]
> @MatiasElo After update dpdk to 20.11.5, I notice the dpdk libs is changed.
> Eg: librte_pmd* --> librte_net*
> So I think this file needs some update. Thanks.

Thanks, with DPDK v20.11 (uses meson and pkg-config) adding driver dependencies manually should be unnecessary, but I'll check if something needs to be updated.

**Comment by chrhong** [comment]
I have this issue since I use the librte_net_bond, but it doesn't link automatically with odp v1.36...
```
../../lib/.libs/libodp-linux.so: undefined reference to `rte_eth_bond_slaves_get'
../../lib/.libs/libodp-linux.so: undefined reference to `rte_eth_bond_8023ad_slave_info'
```
 I must add the lib manually while compiling.

If I compile odp without "--enable-dpdk-shared", then static libs could be used correctly but a new compile issue occurs which I asked you month ago:
```
/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: cannot find : No such file or directory
collect2: error: ld returned 1 exit status
make[2]: *** [../../lib/libodp-linux.la] Error 1
make[2]: Leaving directory `/workspace/odp/platform/linux-generic'
make[1]: *** [all] Error 2
```

There should be something wrong and I notice the odp_dpdk.m4, but I am not sure, just for your information.

**Comment by MatiasElo** [comment]
> I have this issue since I use the librte_net_bond, but it doesn't link automatically with odp v1.36...
> 
> ```
> ../../lib/.libs/libodp-linux.so: undefined reference to `rte_eth_bond_slaves_get'
> ../../lib/.libs/libodp-linux.so: undefined reference to `rte_eth_bond_8023ad_slave_info'
> ```
> 
> I must add the lib manually while compiling.
> 
> If I compile odp without "--enable-dpdk-shared", then static libs could be used correctly but a new compile issue occurs which I asked you month ago:
> 
> ```
> /opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: cannot find : No such file or directory
> collect2: error: ld returned 1 exit status
> make[2]: *** [../../lib/libodp-linux.la] Error 1
> make[2]: Leaving directory `/workspace/odp/platform/linux-generic'
> make[1]: *** [all] Error 2
> ```
> 
> There should be something wrong and I notice the odp_dpdk.m4, but I am not sure, just for your information.

Okay, could you please open a new issue with the used software versions and configuration options etc.? It's easier to track than using this closed PR :)

**Comment by chrhong** [comment]
Not sure if this is real an issue, but may be we could do something to make this automatically.

I use net_bond in my app, example:
```
#include <rte_eth_bond.h>
#include <rte_eth_bond_8023ad.h>
...
slave_count = rte_eth_bond_slaves_get(port_id, slaves, DPDK_MAX_BOND_SLAVES);
...
rte_eth_bond_8023ad_slave_info(port_id, slaves[i], &slave_info);
...
```
Then it would compile failed with dpdk 20.11.5. I check the dpdk libs by pkg-config and there is no any rte_net_* libs.
```
[root@test_dev odp]# pkg-config --libs libdpdk
-Wl,--as-needed -L/usr/local/dpdk/lib64 -lrte_node -lrte_graph -lrte_bpf -lrte_flow_classify -lrte_pipeline -lrte_table -lrte_port -lrte_fib -lrte_ipsec -lrte_vhost -lrte_stack -lrte_security -lrte_sched -lrte_reorder -lrte_rib -lrte_regexdev -lrte_rawdev -lrte_pdump -lrte_power -lrte_member -lrte_lpm -lrte_latencystats -lrte_kni -lrte_jobstats -lrte_ip_frag -lrte_gso -lrte_gro -lrte_eventdev -lrte_efd -lrte_distributor -lrte_cryptodev -lrte_compressdev -lrte_cfgfile -lrte_bitratestats -lrte_bbdev -lrte_acl -lrte_timer -lrte_hash -lrte_metrics -lrte_cmdline -lrte_pci -lrte_ethdev -lrte_meter -lrte_net -lrte_mbuf -lrte_mempool -lrte_rcu -lrte_ring -lrte_eal -lrte_telemetry -lrte_kvargs  
```

Then I rewrite DPDK_LIBS before configuration like this:
```
INSTALL_PATH=/usr/local
CONF_DPDK="--enable-dpdk --enable-dpdk-shared --enable-dpdk-zero-copy"
CONF_LOG="--enable-debug-print --enable-helper-debug-print"

export DPDK_LIBS=`pkg-config --libs libdpdk`"-lrte_net_bond"

./bootstrap
./configure --prefix=$INSTALL_PATH $CONF_DPDK --with-libcli-path=$INSTALL_PATH 
make -j && make install
```

Then it works.

**Comment by MatiasElo** [comment]
Okay, since you are using these functions in your application code, you should link the missing drivers in your build system. We have removed all DPDK driver specific code from the ODP implementation because of these linking issues.

PMDs are private DPDK dependencies, so they should be shown if you run:
`pkg-config --libs libdpdk --static`

The static linking issue you mentioned seems to be RedHat specific. Which version are you using?

**Comment by chrhong** [comment]
Actually, I use those bond api in "pktio/dpdk.c". But you are right, those pmd libs are dpdk private dependencies.

I use centos 7.9.
